### ISSUE TITLE
tests_views.py:777-778: Collapse too many tags on category...

### ISSUE THREAD

**Issue by 0pdd** [fidals/stroyprombeton#374]
The puzzle `362-37ae24cb` from #362 has to be resolved: 

https://github.com/fidals/stroyprombeton/blob/be8f541e13059b68bb11474408565a1768a77562/stroyprombeton/tests/tests_views.py#L777-L778

The puzzle was created by duker33 on 11-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by duker33** [comment]
@artemiy312 suggested to this approach in related PR.
This is not good for us, i think because in high level categories full set of options can contain 200 items.
But low level categories don't have this problems
![image](https://user-images.githubusercontent.com/3526796/50041680-884fad80-0069-11e9-8115-81212cbed364.png)

It's true, that we somehow should limit number of shown options. And we already has mech to limit it: it's subcategories. Subcategory link limit everything in clear way: set of products and set of options.
So, we should just create clear hint with text: "Click on subcategory to see set of it's options"

**Comment by duker33** [comment]
@artemiy312 approved related PR without any comment here.
So, discussion is not needed, i suggest

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#379](https://github.com/fidals/stroyprombeton/issues/379), [#380](https://github.com/fidals/stroyprombeton/issues/380) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#379](https://github.com/fidals/stroyprombeton/issues/379), [#380](https://github.com/fidals/stroyprombeton/issues/380) are still not solved; solved: [#234](https://github.com/fidals/stroyprombeton/issues/234), [#248](https://github.com/fidals/stroyprombeton/issues/248).
