### ISSUE TITLE
Reinit front structure

### ISSUE THREAD

**Issue by duker33** [fidals/stroyprombeton#731]
Till the summer we are going to add some front improvements to the both of sites.
STB for the first place. And SE - for the second.
The main one is the clear autocomplete as stalbeton.pro has.

**Problem**
But our current front arch is too hard to provide any big improvements.
What the problems annoying us right now:
- no import structure. I have no idea where this variable came from
- no typing. I would like the optional one, like python type hints
- limited classes functionality. We are having pseudo-classes implemented with modules. But we can't work in OOP
- no unit testing. We can reduce selenium tests problem with js unit tests. And reduce debugging. Seems we are starting every feature or fix with debugging in the browser

**Choose a framework**
Few years later we decided not to use any js framework since our codebase is simple. But now the time has come. I think we should not invent our own genius structure and take the ready one using some framework.

I see these two roads we can start going:
- *no swiss tool* framework, just structure. For ex: backbone, jquery, chai+mocha, +15 small libs
- *swiss tool* framework. Only three options choosing one of the monsters: Angular, React, Vue

**Comment by duker33** [comment]
the task has our usual discussion format: i and Artemiy split the budget 50/50.
Task result: short comment with a chosen way for the structure

**Comment by duker33** [comment]
i'm not fully sure, but i would prefer to go to some swiss tool. I believe we aren't able to create a more good arch, then swiss tool already has done. And that's my priorities: Vue, React, Angular.

I'm having just shallow ideas about these three monsters, but let me write some about them:
- Vue is the most lightweight and flexible. It would require less efforts to migrate on then two other options
- React is the most stable, with one-way-to-do-it philosophy inside. But it's built on the monolithic idea about nested components with events bubbling, so it hardly dictates arch to us
- Angular has gathered all disadvantages React has, but one huge more. It's built around it's own ideas having nothing common with common known arch patterns

Let me repeat myself: i'm having very shallow knoledge about these monsters, so i can mistake.
There are materials i have learned or will learn to make decision:
- [28 min ru videous](https://www.youtube.com/watch?v=FFZfmIQ9I44&list=PLvTBThJr861yew_0p-x_4DlXh6wTGjkPX) about Vue.js pros and cons. I love arch manner this guy talking
- The first lection about React. See [the list of lections](https://www.youtube.com/watch?v=e_KLk92LLvU&list=PLvTBThJr861xh3fCMf91Ip5_r6TdR15O9). It's from the same guy

And i would add some typing to JS: Typescript or Flow. Explored no of them yet.

@artemiy312 , now it's your move

**Comment by artemiy312** [comment]
This issue has long been in all our projects. These days it’s too hard to keep the front-end thin and produce fine ui/ux
>no unit testing

It is top pain in our projects for me.

**Comment by artemiy312** [comment]
I'd prefer a framework with battery includes too to have a deal with cohesive parts and avoid finding libs those will fit to a project.
>Vue, React, Angular

I don't know too much about this trinity. But only Vue and Angular are battery included and provide the default way to do common need things.

Right now I like Vue most, because it seems it simpler to bring it to projects and it isn't so monolithic as Angular. But Angular is [built in Typescript](https://www.typescriptlang.org/docs/handbook/angular.html) and as result it has good docs to work in the language.

**Comment by duker33** [comment]
there are some thoughts about [integrations between Vue and TS](https://sobolevn.me/2019/06/really-typing-vue) from guys who like both of them. Don't know how it really helps, but seems there are some options to reduce the TS integration problem

**Comment by duker33** [comment]
@artemiy312 , we decided to take Vue, i suppose.
If it's true, we'll just take it's recommended code structure and we can close this task

**Comment by artemiy312** [comment]
@duker33 Let's decide how are we going to integrate Vue to projects:
- In most cases Vue projects are single page applications. They render templates with data from REST api. Sometimes in order to improve SEO they use [server side rendering (SSR)](https://vuejs.org/v2/guide/ssr.html). I believe it is later for SPA approach, but we can use our django templates for static content and use vue for dynamic parts. It will save our time and we haven't to messing around with SSR and migrating to REST. Also some people use vue inside [django templates](https://vsupalov.com/vue-js-in-django-template/) 
- Will we rewrite front entirely in Vue or just some parts? I believe we should start from more dynamic parts of front and migrate them iteratively to Vue as necessary. And maybe someday we will completely migrate

**Comment by duker33** [comment]
@artemiy312 , seo and fast content receiving are the main goals of our app. So, we should use only server side rendering with Java, i think. So, we should use Vue only for some parts all the times. For the cart for example

**Comment by duker33** [comment]
task was finished before canceling from business
